---
# file: roles/btmux/tasks/install_upstart_unit.yml

- name: copy upstart unit
  template: >
    src=etc/init/btmux.conf
    dest=/etc/init/btmux.conf
    owner=root group=root mode=0644
  sudo: True
  notify: restart btmux

- name: Reload | init
  command: initctl reload-configuration
  sudo: True

- service: name=btmux enabled=yes
  sudo: True